In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('C:/Users/Dell/Desktop/data-set/Health_AnimalBites.csv')

In [3]:
data.head(10)

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
5,1989-11-24 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40211,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
6,1990-02-08 00:00:00,DOG,NaN,FEMALE,BLACK/WHIT,1.0,1990-02-13 00:00:00,40203,NO,BODY,1990-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
7,1990-02-22 00:00:00,DOG,NaN,MALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,1990-02-23 00:00:00,RELEASED,NaN,NaN,UNKNOWN
8,1990-08-02 00:00:00,DOG,NaN,MALE,BROWN,NaN,NaN,NaN,NO,BODY,1990-08-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
9,1990-08-19 00:00:00,DOG,NaN,UNKNOWN,BRN-TAN,NaN,NaN,NaN,NO,BODY,1990-08-20 00:00:00,RELEASED,NaN,NaN,UNKNOWN

In [4]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,NaN,NaN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

# Checking for duplications

In [6]:
duplicate_rows = data.duplicated()
print('Number of duplicate rows: ', duplicate_rows)

Number of duplicate rows:  0       False
1       False
2       False
3       False
4       False
        ...
8998    False
8999    False
9000    False
9001    False
9002    False
Length: 9003, dtype: bool

# Filling Missing Values

In [8]:
print(data['bite_date'].isna())

0       False
1       False
2       False
3       False
4       False
        ...
8998    False
8999    False
9000    False
9001    False
9002    False
Name: bite_date, Length: 9003, dtype: bool

In [9]:
print(data['SpeciesIDDesc'].isna())

0       False
1       False
2       False
3       False
4       False
        ...
8998    False
8999    False
9000    False
9001    False
9002    False
Name: SpeciesIDDesc, Length: 9003, dtype: bool

In [10]:
print(data['BreedIDDesc'].isna())

0        True
1        True
2        True
3        True
4        True
        ...
8998     True
8999    False
9000    False
9001    False
9002    False
Name: BreedIDDesc, Length: 9003, dtype: bool

In [11]:
data['BreedIDDesc'].unique()

array([nan, 'GERM SHEPHERD', 'DACHSHUND', 'PIT BULL', 'SHIH TZU',
       'COCKER SPAINEL', 'CHICHAUHUA', 'BEAGLE', 'CHOW CHOW', 'OTHER',
       'BOXER', 'AAUST. TERR.', 'GOLD RETRIEVER', 'LABRADOR RETRIV',
       'BULLMASTIFF', 'BORDER COLLIE', 'POMERANIAN', 'YORKSHIRE TERRIER',
       'GREYHOUND', 'ROTTWEILER', 'AMER. BULL DOG', 'DALMATIAN', 'HUSKY',
       'BULL DOG', 'MASTIF', 'GREAT PYRENEESE', 'GREAT DANE', 'POODLE',
       'SIBERAN HUSKY', 'WEIMARANER', 'CORGI', 'BOSTON TERRIER',
       'SCHNAUZER', 'BASSET HOUND', 'MIN PIN', 'WELSH CORGI',
       'AM BULLDOG', 'SAMOYED', 'MALTASE', 'AKITA', 'SHELTIE',
       'LHASA APSO', 'SAINT BERNARD', 'AIREDALE TER.', 'AM. ESKIMO',
       'BICHON FRISE', 'PUG', 'DOBERMAN', 'DOTSON', 'NEW FOUNDLAND',
       'BERNESEN MT.', 'HAVANESE', 'ENGLISH SETTER', 'SHAR-PEI',
       'COCKAPOO', 'OLD ENG SHP DOG', 'WESTIE', 'BOUVIER', 'RAT TERRIER',
       'SHEEP DOG', 'HEELER', 'PEKINGESE', 'FOX TERRIER MIX',
       'ENGLISH BULLDOG', 'BORDER COLLIE M', 'BASANJI', 'PYRENES',
       'BLOOD HOUND', 'COLLIE', 'ALASK. MALAMUTE', 'BRITNEY SPANIEL',
       'BICHON FRESE', 'FOX TERRIER', 'BLUE HEELER', 'CATAHOULA',
       'CANE CORSO', 'IRISH SETTER', 'ENGLISH SHEPARD', 'ENG. MASTIFF',
       'BLACK LAB', 'SCOTTISH TER.', 'LAKELAND TER.', 'COON HOUND',
       'CHOCOLATE LAB.', 'BOX TERRIER', 'CATTLE DOG', 'SPITZ',
       'TOY POODLE', 'FRENCH BULLDOG', 'BRIARD', 'ST BERNARD',
       'GOLDEN LAB', 'TOY FOX TERRIER', 'RED HEELER', 'WEINER DOG',
       'MALAMUTE', 'IRISH SPANIEL', 'BESINJI', 'BEARDED COLLIE',
       'STAN POODLE', 'AMER FOX HOUND', 'IRISH WOLFHOUND'], dtype=object)

In [12]:
data['BreedIDDesc'].fillna('UNKNOWN', inplace = True)

In [13]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,NaN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

In [14]:
print(data['GenderIDDesc'].isna())

0       False
1       False
2       False
3       False
4       False
        ...
8998     True
8999    False
9000    False
9001    False
9002     True
Name: GenderIDDesc, Length: 9003, dtype: bool

In [15]:
data['GenderIDDesc'].fillna('UNKNOWN', inplace = True)

In [16]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

In [18]:
data['color'].fillna('BLACK', inplace = True)

In [19]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

In [20]:
data['vaccination_yrs'].fillna('UNKNOWN', inplace = True)

In [21]:
data['vaccination_date'].fillna('UNKNOWN', inplace = True)

In [22]:
data['victim_zip'].fillna(40229, inplace = True)

In [23]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

In [24]:
data['AdvIssuedYNDesc'].fillna('UNKNOWN', inplace = True)

In [25]:
data['WhereBittenIDDesc'].fillna('BODY', inplace = True)

In [26]:
data['quarantine_date'].fillna('UNKNOWN', inplace = True)

In [28]:
data['DispositionIDDesc'].fillna('UNKNOWN', inplace = True)

In [29]:
data['head_sent_date'].fillna('UNKNOWN', inplace = True)

In [30]:
data['release_date'].fillna('UNKNOWN', inplace = True)

In [31]:
data['ResultsIDDesc'].fillna('ResultsIDDesc', inplace = True)

In [32]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229,NO,BODY,1990-10-02 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229,NO,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204,UNKNOWN,HEAD,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc

In [33]:
data.isna()

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9000,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9001,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9002,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Data does not contain now any duplications or NAN values means we can proceed

In [37]:
from sklearn.preprocessing import MinMaxScaler
import re
scaler = MinMaxScaler()
data['victim_zip'] = data['victim_zip'].apply(lambda x: re.sub("[^0-9]", "", str(x)))
data['victim_zip'] = data['victim_zip'].astype(float)
scaler.fit(data[['victim_zip']])
data['victim_zip_scaled'] = scaler.transform(data[['victim_zip']])

In [38]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc,victim_zip_scaled
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229.0,NO,BODY,1985-05-05 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218.0,NO,BODY,1986-02-12 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219.0,NO,BODY,1990-05-07 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229.0,NO,BODY,1990-10-02 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229.0,NO,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204.0,UNKNOWN,HEAD,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000087
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072

In [39]:
data['BreedIDDesc'].fillna('UNKNOWN', inplace = True)

In [40]:
data['SpeciesIDDesc'].unique()

array(['DOG', 'CAT', 'BAT', 'RACCOON', 'OTHER', 'RABBIT', nan, 'HORSE',
       'SKUNK', 'FERRET'], dtype=object)

In [41]:
data['SpeciesIDDesc'].fillna('OTHER', inplace = True)

In [42]:
size_mapping = {'DOG': 1, 'CAT': 2, 'BAT': 3, 'RACCOON': 4, 'OTHER': 5, 'RABBIT': 6, 'HORSE': 7, 'SKUNK': 8, 'FERRET': 9}
data['SpeciesType'] = data['SpeciesIDDesc'].map(size_mapping)

In [43]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc,victim_zip_scaled,SpeciesType
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229.0,NO,BODY,1985-05-05 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218.0,NO,BODY,1986-02-12 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219.0,NO,BODY,1990-05-07 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229.0,NO,BODY,1990-10-02 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229.0,NO,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204.0,UNKNOWN,HEAD,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000087,1
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1

In [44]:
gender_mapping = {'FEMALE': 1, 'MALE': 2, 'UNKNOWN': 0}
data['genders'] = data['GenderIDDesc'].map(gender_mapping)

In [45]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc,victim_zip_scaled,SpeciesType,genders
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229.0,NO,BODY,1985-05-05 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,1
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218.0,NO,BODY,1986-02-12 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,0
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219.0,NO,BODY,1990-05-07 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,0
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229.0,NO,BODY,1990-10-02 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,2
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229.0,NO,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,0
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204.0,UNKNOWN,HEAD,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,2
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000087,1,2
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,1
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,0

In [46]:
data['WhereBittenIDDesc'].unique()

array(['BODY', 'HEAD', 'UNKNOWN'], dtype=object)

In [47]:
bitten_area_mapping = {'BODY': 1, 'HEAD': 2, 'UNKNOWN': 0}
data['whereBitten'] = data['WhereBittenIDDesc'].map(bitten_area_mapping)

In [48]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc,victim_zip_scaled,SpeciesType,genders,whereBitten
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229.0,NO,BODY,1985-05-05 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,1,1
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218.0,NO,BODY,1986-02-12 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,0,1
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219.0,NO,BODY,1990-05-07 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,0,1
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229.0,NO,BODY,1990-10-02 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,2,1
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229.0,NO,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,0,0
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204.0,UNKNOWN,HEAD,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,2,2
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000087,1,2,0
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,1,1
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,0,1

In [49]:
data['ResultsIDDesc'].unique()

array(['UNKNOWN', 'NEGATIVE', 'ResultsIDDesc', 'POSITIVE'], dtype=object)

In [52]:
result_is_mapping = {'UNKNOWN': 0, 'POSITIVE': 1, 'NEGATIVE': 2, 'RESULTIDDESC': 3}
data['results'] = data['ResultsIDDesc'].map(result_is_mapping)

In [59]:
data['results'].fillna(0, inplace = True)

In [60]:
data

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc,victim_zip_scaled,SpeciesType,genders,whereBitten,results
0,1985-05-05 00:00:00,DOG,UNKNOWN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229.0,NO,BODY,1985-05-05 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,1,1,0.0
1,1986-02-12 00:00:00,DOG,UNKNOWN,UNKNOWN,BRO & BLA,UNKNOWN,UNKNOWN,40218.0,NO,BODY,1986-02-12 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,0,1,0.0
2,1987-05-07 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40219.0,NO,BODY,1990-05-07 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,0,1,0.0
3,1988-10-02 00:00:00,DOG,UNKNOWN,MALE,BLA & BRO,UNKNOWN,UNKNOWN,40229.0,NO,BODY,1990-10-02 00:00:00,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,2,1,0.0
4,1989-08-29 00:00:00,DOG,UNKNOWN,FEMALE,BLK-WHT,UNKNOWN,UNKNOWN,40229.0,NO,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,0.000072,1,1,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8998,2017-09-05 00:00:00,DOG,UNKNOWN,UNKNOWN,BLACK,UNKNOWN,UNKNOWN,40243.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,0,0,0.0
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,UNKNOWN,UNKNOWN,40204.0,UNKNOWN,HEAD,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,2,2,0.0
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,UNKNOWN,UNKNOWN,47130.0,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000087,1,2,0,0.0
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,1,1,0.0
9002,2017-09-07 00:00:00,DOG,BOXER,UNKNOWN,BRN BLK,UNKNOWN,UNKNOWN,40229.0,UNKNOWN,BODY,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,ResultsIDDesc,0.000072,1,0,1,0.0

# Now that we got our features and labels right lets move to ML Models

In [61]:
X = data[['SpeciesType', 'genders', 'whereBitten', 'victim_zip_scaled']]
y = data['results']

In [62]:
X

      SpeciesType  genders  whereBitten  victim_zip_scaled
0               1        1            1           0.000072
1               1        0            1           0.000072
2               1        0            1           0.000072
3               1        2            1           0.000072
4               1        1            1           0.000072
...           ...      ...          ...                ...
8998            1        0            0           0.000072
8999            1        2            2           0.000072
9000            1        2            0           0.000087
9001            1        1            1           0.000072
9002            1        0            1           0.000072

[9003 rows x 4 columns]

In [63]:
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
8998    0.0
8999    0.0
9000    0.0
9001    0.0
9002    0.0
Name: results, Length: 9003, dtype: float64

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# KNN

In [65]:
from sklearn import neighbors, metrics

In [66]:
knn = neighbors.KNeighborsClassifier(n_neighbors = 25, weights = 'uniform')

In [67]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=25)

In [68]:
prediction = knn.predict(X_test)

In [69]:
print(prediction)

[0. 0. 0. ... 0. 0. 0.]

In [70]:
accuracy = metrics.accuracy_score(y_test, prediction)
print("accuracy", accuracy)

accuracy 0.9722376457523598

# Linear Regression

In [71]:
from sklearn import linear_model

In [73]:
l_reg = linear_model.LinearRegression()

In [75]:
model = l_reg.fit(X_train, y_train)

In [76]:
l_predictions = model.predict(X_test)

In [77]:
print(l_predictions)

[-0.0164478   0.03984739  0.13681758 ...  0.00228427 -0.0164478
 -0.0164478 ]

In [78]:
print("R^2", l_reg.score(X, y))

R^2 0.10288985898377945

# SVM

In [79]:
from sklearn import svm

In [80]:
SVM = svm.SVC()

In [81]:
SVM.fit(X_train, y_train)

SVC()

In [83]:
from sklearn.metrics import accuracy_score
svm_predictions = SVM.predict(X_test)
svm_acc = accuracy_score(y_test, svm_predictions)

In [84]:
print(svm_predictions)
print(svm_acc)

[0. 0. 0. ... 0. 0. 0.]
0.9711271515824542